export const COLOR_RED = '#e1382d'
export const COLOR_GREEN = '#46b02e'
export const COLOR_BLACK = '#252f3e'
export const COLOR_GREY = '#FBFBFD'
export const COLOR_LIGHT_BLUE = '#eef2f6'
export const COLOR_WHITE = '#FFFFFF'
